apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  repo: https://bitnami-labs.github.io/sealed-secrets
  chart: sealed-secrets
  version: 2.15.4
  targetNamespace: kube-system
  valuesContent: |-
    fullnameOverride: sealed-secrets-controller
    commandArgs:
      - --update-status
    keyrenewperiod: "720h"
