apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  mountOptions:
    - vers=4.1
    - proto=tcp
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.0.0.22
    path: /mnt/Zpool/Apps/Container/uptime-kuma


