apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: uptime-kuma
spec:
  storageClassName: ""
  volumeName: uptime-kuma-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


