apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.namespaces: |
    - argocd
    - monitoring
  repositories: |
    - name: grafana
      type: helm
      url: https://grafana.github.io/helm-charts
