apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-server-ingress.yaml
  - argocd-cmd-params-cm.yaml
  - github-ssh-secret-sealed.yaml

namespace: argocd

# Note: ConfigMap and AppProject patches are applied directly to existing resources
# in the cluster rather than through kustomization since they already exist

