apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring-namespace.yaml
  - argocd-controller-rbac-monitoring.yaml

namespace: argocd

patchesStrategicMerge:
  - argocd-cm-patch.yaml

