apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    # Enable Kubernetes auth method
    auth "kubernetes" {
      path = "kubernetes"
      kubernetes_host = "https://kubernetes.default.svc.cluster.local"
      kubernetes_ca_cert = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    }
    
    # Enable KV secrets engine
    secrets "secret" {
      path = "secret"
      type = "kv"
      options = {
        version = "2"
      }
    }
    
    # Policy for external-secrets
    policy "external-secrets" {
      path "secret/data/*" {
        capabilities = ["read"]
      }
    }
    
    # Kubernetes auth role for external-secrets
    auth "kubernetes" {
      role "external-secrets" {
        bound_service_account_names = ["external-secrets"]
        bound_service_account_namespaces = ["external-secrets-system"]
        policies = ["external-secrets"]
        ttl = "1h"
      }
    }
