apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault-init
      restartPolicy: OnFailure
      containers:
      - name: vault-init
        image: hashicorp/vault:1.15.2
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Vault to be ready
          until vault status 2>/dev/null; do
            echo "Waiting for Vault..."
            sleep 5
          done
          
          # Check if already initialized
          if vault status | grep "Initialized.*true"; then
            echo "Vault already initialized"
            exit 0
          fi
          
          # Initialize Vault (one-time only)
          echo "Initializing Vault..."
          vault operator init -key-shares=1 -key-threshold=1 -format=json
          
          echo ""
          echo "=== NEXT STEPS ==="
          echo "1. Copy the unseal key from above"
          echo "2. Create secret: kubectl create secret generic vault-unseal-keys --from-literal=unseal_key='<UNSEAL_KEY>' -n vault"
          echo "3. Restart Vault pod to trigger auto-unseal"
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-init
  namespace: vault
