apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    # Transit auto-unseal configuration
    seal "transit" {
      address     = "http://vault-unseal.vault-unseal.svc.cluster.local:8200"
      token       = "hvs.placeholder"  # This will be replaced with actual token
      disable_renewal = "false"
      key_name    = "unseal-key"
      mount_path  = "transit/"
    }

    # Enable Kubernetes auth method
    auth "kubernetes" {
      path = "kubernetes"
      kubernetes_host = "https://kubernetes.default.svc.cluster.local"
      kubernetes_ca_cert = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    }

    # Enable KV secrets engine
    secrets "secret" {
      path = "secret"
      type = "kv"
      options = {
        version = "2"
      }
    }

    # Policy for external-secrets
    policy "external-secrets" {
      path "secret/data/*" {
        capabilities = ["read"]
      }
    }

    # Kubernetes auth role for external-secrets
    auth "kubernetes" {
      role "external-secrets" {
        bound_service_account_names = ["external-secrets"]
        bound_service_account_namespaces = ["external-secrets-system"]
        policies = ["external-secrets"]
        ttl = "1h"
      }
    }
