---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBEybRzbIq2pxTi7T5sysIK8+YWeXiWX3D+lkHqCzvNE84OK5pDj0Oc+IheefN0Jtyy8H+PmGsYnq4g3+RC7gTwCY6AcUa8GN5C702M4fkVQyx8Onlo4C2zzJfRejsWbiwk2ebK+1eUovY/fdFddlBHRiq5+bZdQ6lS4YGHzreQJUEfUIBkDDhlDcsBMlTADRCxkXnTi6oKV739byvMFravie6i3tZz1XXMqcgzPAfFIwkvIJAyB5QhuFOBd0eMVUccQ8t/gLg/dHtfWDwdSOpSDl7fEJaHq/gCK0MpBhDweW8xY5Xhg78bM3+SdV5bpWg04xX/P6JoBTasoSjC+NRTpMMZfDSXZtWLFWhb1cu0DHSMeG08AXOyfBk54ztIKm8mfl8TL5EhSD+sEeHbe4CxC//RKUKICXf7DdbWaCQU9zKTXExjLESaTj8Es5jrRihk4IJyMjSqyWxiA0zj0VR8zZZTholwxGLxA4+1l0mQRiguwGfVKUSavfsthY+q5sDvJ9vf6LlfYHB8fgor/+bwRnFYh1YbuQAVFnkh2jIudMW1jxYd7Nsg7LYs8D/Gu+v6Va+EyLmErrgP2o0Zk22a+8XgM+VqoytRykSjy5/KXRJas5SMdTdSeLgYotVDtEPGFp229M1ss8ygqGztAoyAnasq3WWovVIiXGS8YSWcHn8Qx1s8dBKnx2Z4QkRyH/su3ZQ0gxm5Rw==
    user: AgBf2oywjQsJUED99ICqp6B+RRfQrrgRrLSVGQLU04NzL1jEtCTkAGwrrSBuR4IppbJUJj9RAv3MQtHPhn7KTozVrcUd744o9QJeDmtN/gl9fCMNEsjtbgqhuSCyF0v6kywZm0RJiHBQNHIOXrNMwVOP9CVR/adzM7Mg7GWZn5QTJqUZ7ti0gbj+uMoSMoxPgt+OQtzkuJ8F1Ffn8sjYywENOPsOeelXCtL10X2BrvTX/seI9FdFnJTB43dxA2Tfs6fHsgyTv27lbuuvtxZ2pSf6N+jV3+L1NWinx6qLOrkA4qXQ1ziJF9YpLphXUgUYr3aumR+m1xbqzF4Ut+TdswML5jEdmXzTwJpM0o2gzDslHjNLRoBVQaQ17g3SNXRlJkqe67nHpjg3t5MzIZC0GHyM+mczCVPZhvD8XXnLi2ElWX0OpuVuDmMxzJ6vdWmIxIGlVh9fTMV3XqrdkG7tr9jaL4HTFG49vOJGq3OmbeN1zGfmK7lvNx5MNgZaVOsqKMUvrhuOJ9GtWS1cuxBNIyKMpr7XGHI22WAs5gXGHW3Xvm3bw6FNWBopk9fBCyVozd4sODtHCWS1a2RwTppJqKs+VlJL3Xj/kWrU7K0BkAch7mg3YxhD+czTcduweqQYFSL/OjRSOj4+TUz1Q8YkGJC05g7355mHjwycb4cDG1YBMp9Wmfo5JzMesk9AoLx87VqnnAQ8Iw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
