---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-api-url
  namespace: monitoring
spec:
  encryptedData:
    slack_api_url: AgAJPuRi+uFXksPtvMw8KJv0Y7M55pW27VWL257/FlnD7fWgPA0vlBhUOPl9B1/P+IeUIMUKwa96VB5lz5QEIOEqCOqwjToxVDBwKfqtOh4OlAf7VUB3SNeCOlFPfgu7Iqb44soYNxBQN9kTrPkAOy3FAuCBEzbZZCosQRQHuUbeFDbDKJjs5iklid/yWzrxhB9tVbC60WzsDRBTCD7OMNJgppU8lHPveCfrBUeQYdUapIhwjXRbyjVig43vNljnTszX+h7YKZaF3AaTnDtDxo2IrBxbm82pXgrZ//L/ZjIjDdzeoqE0WI3i+Vnzuait3BvhxrmOMOj2x1MLuvP1v8Fst2NskEMb5VznpmPoXoWH2bIureraX5BWtIITI5LcTK3JBOVF12xznkejUaWOr3wDoYv27I0T3pnKIvxsBtFNvOA2Rf1ehRuN/IWBm8X3swp6HlU8WfczhJnsigLlIFWvlxwwGxbNgwDK/RPReoUt6S7UMXDf9ydM0/WTzL1rjkryPjAS3kccU4fPP47TUf2BCNAM2J4TFywIhBlpFFloHSFwFOh+mYU/xlcB0BQoaP76Hw5YYAYXnvzVSS5ZFfZVtIF3AT9XRAbjsiZE0TALMV40dt0euk0NYFP8UrWwJ30WwtaUMRny2U73uDqYZqLYGLaSXkJDGbwq+vok2GHBtdkefZt5BSXiHpik5lXWjtIUrcCkb7NTd59RpFRZxW9uFMWh2Tt8jrakGL8yUXs7BwoVUwTjsoLD1XAmmq8q0WodyAT5q1GYsHLMZAvTMud5N8+8mJBRzril5JIu9d70GDU=
  template:
    metadata:
      creationTimestamp: null
      name: slack-api-url
      namespace: monitoring
