---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgC/tuQ+zsol8eJmFyijDK4Bk9eN3L0CKaJ3X8IDSvEVK6f4F3VQr9oC1y6RyahjgsDxNAh1f+dy1MlvCaSHfsLYVZ1QmkpvvpLbhQ6a0RjScWkoMzON/QWHd4MdBi+aiRBRo0+WWX7mNQe/vKLWZjGz5mxUxUCh16p2j0aYefI19+ZnxnPVJzoX4Q0D4pDJW2Hb2C32oiYqSRLHQ3ISufpZGFplbQEOhIqkbkWoDqHCijUHp50mxIbT0A8ZOVXvY1VpzFxf9NqYITFtIgeGYCIaSPnWbsMOpfn14uYVDYEzdoZDMF0LcZ7iTXiYOYo2ia3zCZ5//1h/QZE69tE//P3hA8m+HFk9W6tH+TkLMVj6Wju762CX5VXyG0pOlcroGsdQsjJPntdTFnz1cSpWKb4CvMvmCcgbISzu5HQhfBvR7KF/WF2cL+y0BZ+T3fAhH8wrtVPOYkkC8Wa5iQWQ0EK438dsbPspe2+AQf0BMWcYl3JXhuUWnFeNpf/0emba5/jY75K05vHuZGZypU6cR02uFbHOJXA6TT4taBzPBvX71Xh7zTzgo1/I8b9Ttf1x6SO6P1volsUoCel5Jw8j2oxpBOArUqxTT42qIT084xL9Tl3UKdPhy6hKm2wva6Ja/f7lSvE9qOM5e/GDJJL2hBWYOnFfmtL9EpnN5KlqboZfGRi0/L66pqqC5AHstEsRTHDHMk9FqMSE7A==
    user: AgBvuDHJOzrTLsbmciZeP+ZaZt0H1y2c1T2O9uJcqOIrFNA6P3VEgONiXKhV6+nxIrU/634dY/q8Ih8IUvGCQf5m6oF+bkilSDoRoYPSspA0Jd9SNATT7Va/PYAx7Jglmmb5D1z+yKtQhnxkNPp0kx5/PUx163cQpSSb6HB5Z2CVU5xhcw+8z1am759pcJ2oLPuOE7RtY3JeIv6ox7Cq4tR4pr0tdhxjUL1L6tA4WGeJBqxE2nG8D2FXKjliAOUF7VGmJ46b6+iWn4dRbKyaIM5c8udBXYuO90v4JT+Wr3fljft+pQsZBWPEKKTXaog/ivPoqDfXFYlGreq4kH5cCAVkZYdii0HXw+xTl3s4wsULB7IZiSkkkHJpDt5Ssd/gSnHxPXT22y/rsfh2nvhurEHKYzOGa4f1Tc4OllvfQmLggf1n/iBo+VSuU0MLaT1AAG4dkSR0h0UlwYBowHpK75Sz5Rm/V4b5Y5AHv9QoABOBLP6uN08V3uBLaWZQgOL2Bm97IxT1qDvck7NFHymsvQUUbLoKRPySDgOXlsDf2IEFE2RiqfSuSGflY4V9Pv92/8P2cYLhse8y3taNLQG51wsvzReuI5g7GF1c/1LwB4ZYIfPk0klkIKxj4JcfbfAG5oeJT9bDnQYltCov5pIL/cdW4kf2oOgtgnALuzIHX8/KQex/k/g7br0Xw5PB+L+FJuPr315/Pw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
