apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgAvis2zP8ZPyeBtTIz2ytLtnncwCT7ObhB7el9kP04GKFIOyZyMIdXvHdgw/ePGQKZ1lfllKpsXRmHTUqad61o6eyxVMkfhFmFBvLLgUNFlXX7np5Vyy5bwtgPBjeO4zdMV7wzGqQtXWETj3d0FpbDlvUD7qACscPlgMoTTr4GeSBe5J0Fq+dO8XmgJUUuBZvaZLn3+D8BAPnqaeMDwz+fXl+Euj/dvooPNU+LyWx6VyZHy/fMpxHgZUzitjYREvUktm8f/07DlOfff+1UzAhiFZvOb/guq+tySRQcvoDtchv84NX1r20KA30J9CJ2W7zqwzj+RWgy77f2crQEyl9pRx12xF/h+cC7fZsy2CaP11p5pt14AYsysENxL9HZ6N3Kv3/8cozgM5fiSysGp8n0bIknxELyNaChEZX9iFgAT9cFaQxVQVr9U5etaRdbYDD7kzBKMqM7fRp1HjofE67OYWB5hYW8XdjnGFQkhZRun4WR8y9lUY23gfmQiUenKXabnI0EiXJdhJjpHnhbqOh7n7+ZicFFLuKv4geHGc6eYGOpkZc+4x/wwAVXGvdcfzvBPaN+uSiZkbhWlevg/7MAhsreARX4m/4N956CNIw/kx6ueeH2u9YaHvMfBBwCkwYakMVow9vdl2KDPopXVzZcBd/WWbalT5bmBAmWueY2xG4QQk2J58TOXPpRcSjMzg9BdQOMSDT1SBw==
    user: AgA6r+O2YGA+2qMQCnhoL23yVYx1RAqbhgn1IgDtMrKLi3ghSJQIx4p/+q24IrFkX04gj+otkB1JX7oSwTagwrjZ0NUIPo1w7QFYD6VkfcwfwXV+BWr5jG3d70AnDPgPgeAhomB0ZuSSVMMcsr73fe65f1mV61+wg6LjfU0dSiZU8WyVKdgiEUzBn3eJlIdL25GgSkZrizZUJuBxZap2Mj1FYl1k6Wu2lWOOsm29FJCPuDZFyO6yEDMYTKLon6rG2T8uZxg5srFmvu/dURwJhtOFrM1qd73FKG5l+5JAllOBNQ6AvKHYPPOmH991l3O1UyvnsmFJmJAt5QsfftfD7qwa615VvaFPioPvwZgLSCqcDeQkS88Wnc02HpLL/McoWIOIPs3dMjXHAHBtZiGRd/bWn7t8UldsYYhYEzm6Dlo2BAwIX31nj7aXElqYaEi8Ny8JVrZHFgQZDdVgy30KQPoG9hipasqRLgynX/phiCJXQ1JRL5G1VifuEeCuxq345K04znBmMlu2zeiGFdWMumzEAi/c7L+ihqGsscXfRpNsIpt1MQk0Me8d/9BMC6ed+YxsjGDn9fw0AhKhpavVrVtyK/hHOrQFpBH2/iOS8LofO/uCo0bGWHKJPIm0GUg5D9/BgLO483vzjy/kmPA26HQvO8SsSLupHqT8lv313JQdE74d8UbkReE67U/ISSufRDzlzKq3HA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
