---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    password: AgDEl8MIuusfo13xhpURy1IiW2QXpf1zmEibqLY58oapNIU4vduGecgAih8Yl6rZk7ogwpKl+31ezey+g9mBc+7Wq6aBAoEiVtZpiDElYW5Z9cp3M0BE4eoKRA1D70IXwbqyM6GfGgnzKLvgZYQSZWWR5dEBYGRGm2WH2Fxshb6cLItuF2WPkthNZUGWLCaDDI+6HJNL0I1/a1YTIKlIJ9FjBhPWdd0N+8IJeOK9Xl74yDcjW7EHKwJvFy1igtMHyuxGP5iUzvjZEGCQFomLiwPv1j1BRmFV++MA3/a/t0kN6v1a0BoFtDj4x9V89j+KOXRVPe5vdTtdexD4FBP+ZLg6TmbBEmh1Q9Ol3VKhxMlBLUpgnj4T1hi8lOLJ9Quipv8GDtPQAQA5kLuR8NeWlRMAthsqIwWgW9jZfgtZ50rVqA/DDPOUkeVTDLhaBmxBBaU1+hKWJvsy7t2nU++csfOqJkn1mxP2tPwn2/2OgqeCvLXLeumQDS6Lofm9Uv4NFfjROgC2i4YAHXMIEZPBjMAk1A7ESrx2MlXkMVVe94MBlEN7VcplKeyFHD+pBrtnc/UHkPPqZBUOKUCeJVJhkcy42DsGZqftAjouxn7ZqDVs15geHNdG6XNqgh0AvqLCbAp+ycZpHlow0w+QdqukT1YadtcPKRCTnmpANo4Qzp2R+vCpuoz45/bp1zAy96GUTA8/xFIJs0+vmG0b3d9n1Y0O
    user: AgAE43ipDVkzzl4Le8RuufFxc+TfL82d3oJyZXOiGePxcgMjRZ2XYAVgHFGo/8lyLwCGAXx+6Z7U21aV3z7TAMMtuEAemu0Ah+fXQ60ZE2Yinz4jqnjiLz6v+GnyG3eg9Bnl88T/i+RrCBQio+99EavfFjGNvZ9hZuXHIsXvVyEmos5Y8gVxQoGalgMYW/zElpTobNEDllL+XUBXj+g9jZgKEn6B7dZ0PCYXlODEBSAH8w85IVaesnWqVOfxwDnjTPC96YsxnIKY61opXAEgwAhqyixetBgFHPWWwYhhZBoH8R1JsaWWMvAdS2BEDLk2Kz9Mi+K43yoxHedvUJxia7kbfvALy++tdj1C2zC7Ba+r3zQhik9F48E5uXYMIztbH6bCjj4ISMvStjUMceROi1WNizbrPnyplvwqCY+7xGal7gqiE29PqG0ZlfZm3SBTfqcEbyYqzIrHqCTJlgjdk5RgyqHtuYoyLE7/De10Sx1cDHp5/zYR9MbG1Tpo5mXEMB6zUthbQCwrvKLX9/WLOXrQArRFHdm7DlPOyMwzae3liNxiAnpfE1Qex5REiMzjtLEuGEOqwOUQRCoUiYUOXC4EuC8NWDHy5nc6bHdkvQRaVsJrT/OlGG2Y3FUXQ8uhzz2M3Ni0FMWVAFJtp4944JV62KLmloPvqKZ7x0vrw50ARODxcB+UcV6UwyQYdg7DgmYLVM62GA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
