apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"  # Specify a version if needed
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    prometheus:
      enabled: true
      prometheusSpec:
        scrapeInterval: "10s"
        evaluationInterval: "20s"
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        ruleNamespaceSelector: {}
        ruleSelector: {}
        scrapeConfigSelector: {}
        scrapeConfigNamespaceSelector: {}
      persistentVolume:
        existingClaim: prometheus-pvc
      enableAdminAPI: true
      enableFeatureGates:
        - default
        - remote-write-receiver
    
    grafana:
      enabled: true
      admin:
        existingSecret: grafana-admin
        userKey: user
        passwordKey: password
      service:
        type: ClusterIP
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - grafana.local
      defaultDashboardsEnabled: true
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          folder: /var/lib/grafana/dashboards
        datasources:
          enabled: true
          label: grafana_datasource
      persistentVolume:
        existingClaim: grafana-pvc
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: "http://loki-stack.monitoring.svc.cluster.local:3100"
              access: proxy
              isDefault: false
    
    alertmanager:
      enabled: true
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: alertmanager-config
        logFormat: json
      persistentVolume:
        existingClaim: alertmanager-pvc
      config:
        enabled: true
        name: alertmanager-config
    
    kubeStateMetrics:
      enabled: true
    
    nodeExporter:
      enabled: true
    
    kubelet:
      enabled: true
      serviceMonitor:
        enabled: true
    
    coreDns:
      enabled: true
      serviceMonitor:
        enabled: true
    
    kubeApiServer:
      enabled: true
      serviceMonitor:
        enabled: true
    
    kubeControllerManager:
      enabled: true
      serviceMonitor:
        enabled: true
    
    kubeScheduler:
      enabled: true
      serviceMonitor:
        enabled: true
    
    kubeProxy:
      enabled: true
      serviceMonitor:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-adapter
      version: "*"  # Specify a version if needed
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    prometheus:
      url: "http://kube-prometheus-stack-prometheus.monitoring"
