apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"  # Specify a version if needed
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        scrapeInterval: "10s"
        evaluationInterval: "20s"
        serviceMonitorSelector:
          matchLabels:
            release: prometheus-stack
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        ruleNamespaceSelector: {}
        ruleSelector:
          matchExpressions:
            - { key: release, operator: Exists }
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
    
    grafana:
      admin:
        existingSecret: grafana-admin
        userKey: user
        passwordKey: password
      service:
        type: ClusterIP
      defaultDashboardsEnabled: true 
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          folder: /var/lib/grafana/dashboards
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
    
    alertmanager:
      enabled: true
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: alertmanager-config
        logFormat: json
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-adapter
      version: "*"  # Specify a version if needed
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      url: "http://kube-prometheus-stack-prometheus.monitoring"
