---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgB0NjFW0oel1isl67oroM0I5CbcXPVZKx7W0yB0UlsU+wv9ubHOYettde6E2m5hZ2OWaDi0XVOxYFO5tuZ1z54vmZ9haTE0RacQZaH2QJi1BKJFI/JMUzxOl2PVbTwLD2++1yke70oNHJUer4s0szmdwr39gxiepQX7dNRNisRp4rphQLJOcmFy/Eq/8TmCjFZ7cUIHrNwfcIyDbC/8s+zM2Zd3S7QIq0za9n9Fg6TtPuMpEwXzumdhbEfag4l2ryNphw2CspmFocUqjeNzYSm4olYOGhmUptcst6Wq7+q5y6omkBHVVmVR116G/w2RYtKnuJ+Oc0W5RNYjY042Y+G1LB9KNqDa9bSgRSRvxt94Ibcs2Lc8Yzk0YJawFAA1duo0/xLyzxusCaWcPlIJzCZtCCqwsnq8xuV7oRwwAyvjIEcxgzl7gWfJtDYoex0IJ3m6zL4AgQuXAEgNhYvjn0kFOQUCbUK6yLPGUCntm1IC9hVAvf7Qm35gNzJy4jcln5EU8phqwa54stHnnvkUTu/kbrtOXHZv91iMnVXxEjiPwb6swOxHtvhZQ+sMAs4B8xqkaCBcA4/L0dATvirMIgHMAX4iVarWWTTTSwdKgybakruaSzDARs0om1Wbgswmzq1mBAOTF8Sjeuh7NYP4lrEza3B+leK4MDUdXGfTWrgD3/0eJ8Aa8XbnIVE1k4HYDgv1N3MHQSf9Iw==
    user: AgC3jKNti4zKc7Y0yAC7I/zvIQMomufj48ILWpr98EekAhdhkXiGn9MdIUdPU/KGpzB8xxgUS8uVxT3sgNVVf0QZKbwSmVtTiY22sf5/+XN88o+2apH6G4lZ6V+JC29bOFW8ihAvXbMbPAcIlQxE3rIHxBO2V4gKvI35A+5dmm+KnTyHBRsl9qpVO/2bjGqpHYvTv8hDTLYHOcSrN8zX75MH/9HHrAxMea8/xCo6G2PwNmn25UOUIEN/7AthEkvRzEYCAX148NzCfiv7UJKsMLBO/myhHKfGdktB1ufVC/indKM5D4C08kqwcVgm68Ps6RoW9rdC3wtZbZIV+zGcS2T5o/L0iaIGWXLIBqY2p8cu0kIT0okZeV8hNqozsOwI9Q0Nsd26hVD4G/EKbCLgNVMkCmiSwzd+F0fN50jN+rjdHa+0NqCnFr89TUVRDoBPST2V4pJ9SEiCPm5qLQ2Xe5nwBiAwuaVK224Z8G8iKgG+tTDd4LPvvnUilP2ZZBC5waMjWrpvnxmRow+uqJagQOCsJl8Huu3RBZiM1L6cFvEKO+UqzQu1DgVVXuzN1LV/AbBH5tcgfBre+v4POzNONjnzYTWOi6unRTzicQ/92XAPzDuBLgYtSUregeNVLV2cFtPk7ovTpXke/l/A6gvXXfcc5pugvAih8EY5IOa2jrA1objzKA8S+M5gjMScpPJrHAl+sN/SdA==
  template:
    metadata:
      creationTimestamp: null
      name: loki-admin
      namespace: monitoring
