apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prometheus-stack-pv
  namespace: monitoring
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Data/docker/kube-prometheus-stack
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: kube-prometheus-stack-pv
  storageClassName: ""