---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC6j+1aGgF/bhAA1eXbu0GGsS7OozoaTwI451V5hWLUeokLJ87z8F252ynkG3ahkdNOIOYKhdixEOk+FDByLHYJltg3dUjhKItpe8YVIO9gpBmeCG31Q0RYw3TKygOY0aSRZ2xhl8pix04D7OoVb/SfTS+Hfqihpy+ns/MssSJ6ixeJg0Jt1ZLeaHdEwHDPqfy2nCR5ISF5lxUEHo4QKJ5EY+In71vF6xN/0ywSil0xPuYoguVT4p2XSlAyg/w0gzK2lyYenQCuu74bQXjv/Niy9gLyCDhrWmExSxcOHfBIVaTP55bCrNde1NCuLUboYeruzQ/HD//lQTlhM0uxiDAeAvhdDnttO6NToC+CjcsYYwwWKPw4DNHy8AjinnNhhgYm0IUJ8bq1QvhG+XhV+EpWYwkeJK6ElOtmNf3IBInjEn+IqP3unjabczn33JspJfFbV9k/PQour/0b+4hYLEDpJGKSUOYD8NxHGSPEydHPlZSdXx+jMsh8G1CHa7sZ71MgcmM1ur/wGTeiaubmbRgnvkyrKTXCwYZiRaS9Bsq4zr72WSBncFEju1nFG1kVTWPpYhsZfE6O1mTMtChSaD2k5a6BDp7k9EUNr31CpGbzCaPygmD9h80BsMCAYINi+edQrEVYQvZRbJ0JxPtkug8rKGogKykPn9rcyPR8PwLd5Pyda+xUmBxD4ykjVNkChx6ZpUX5VSLGGcZbSN90ceGcCw==
    client_secret: AgB5huP+kpAUjMqFMC2cYS2d+5M8EsT9Cc+zkeIy5xYnFnuLvBpOwlInPPXZgMkmUUe//XLKDtHHC9n3qU/H+IRm1+VEgyblJDS4pfImUPjcx3mcF1Rr02fsil/eTc/xYaYQqTvWfAcHEKtzk/DauFshpAPiSHz36+mO/j0tJ152lLmny9gK1pDKGworVlyx+RaJV4Wz3MbNz96wx3enUzV7tjIk8Gzhk1pYKZ95awCRgGB78/r0t876IEVLCoPK3jSpduAjzEt9CLXm9W7jLiqT2ijTIo5BWMcUwM4oQZKNDa7usS1li2Ih5KgbRAcTtUBTl+j8bvEr7oMYP0VCEBFaLcVn7wC/1MsHhWgajHsSc4kgEKEnEo6zSqOkAzmR3+gaZUSeGDw+5RX0WjTVA/z1iwplO1a3hx2Y0CyvWTVlhmcSqRBmSoUlVGxGhLLA8E2FLjKSlkduCs3AV7cyoft/JlGX8CSzHImiJDkxnGMDs7USviVUXs9dKuguHwtp2dfy/NoQ5NAneZtgqHyuFWjE9ExKeez0ZRAu+1HeaXgUbuoYCSWryvJd36O5n3QRTnZz1uO9YHS/Ol3ZjDkSxjbfX/szsYOlNaaOn+5tgKFZwlMf7OwvJj1uGRQfFjbjXvToCiSdQy+RpPNYBJRmRbwSJrcgkV5EOUT9+u89PLzBByrhB7+h7n3y4jL415KDVXzWf0+kFaYbuRxxdE+G2m1Qg044Pj2oymAkJeKvfLHIV/30g9mg6+L9rZAW8kMgkeeaeRxs9U8JMGrTIGLgmhv4
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
