apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: "*"
    helm:
      values: |
        cluster:
          name: home-k3s
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
            auth:
              type: basic
              username: "2600859"
              passwordFrom: grafana-cloud-credentials:access-policy-token
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-036.grafana.net/loki/api/v1/push
            auth:
              type: basic
              username: "1296106"
              passwordFrom: grafana-cloud-credentials:access-policy-token
          - name: grafana-cloud-otlp-endpoint
            type: otlp
            url: https://otlp-gateway-prod-us-east-2.grafana.net/otlp
            protocol: http
            auth:
              type: basic
              username: "1338312"
              passwordFrom: grafana-cloud-credentials:access-policy-token
            metrics:
              enabled: true
            logs:
              enabled: true
            traces:
              enabled: true
        clusterMetrics:
          enabled: true
          opencost:
            enabled: false
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: home-k3s
              prometheus:
                existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                external:
                  url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom
            kepler:
              enabled: true
        annotationAutodiscovery:
          enabled: true
        clusterEvents:
          enabled: true
        nodeLogs:
          enabled: true
        podLogs:
          enabled: true
        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
        alloy-metrics:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-credentials
                    key: access-policy-token
              - name: CLUSTER_NAME
                value: home-k3s
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: false
        alloy-singleton:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-credentials
                    key: access-policy-token
              - name: CLUSTER_NAME
                value: home-k3s
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: false
        alloy-logs:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-credentials
                    key: access-policy-token
              - name: CLUSTER_NAME
                value: home-k3s
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
            remoteConfig:
              enabled: false
        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-credentials
                    key: access-policy-token
              - name: CLUSTER_NAME
                value: home-k3s
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
            remoteConfig:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
