---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-cloud-credentials
  namespace: monitoring
spec:
  encryptedData:
    access-policy-token: AgA2pIyC/ZjUuv5nq5/EkzYs1MYdfeMgjerb6q5h+k9dAYMRt95NqOjh8zCB7SLGc/aZLlnU0pw1Xkd8JM0KHQsLel/2VULKO0DtdxLf8TEjpOKsV4tfOG5OBJD+Jp6iwZ+fwgdGJMC15M2WRe/i26+y1y0iGj0wGfQdOdvstgGUPCbxIXM8M0KK555WVpOm7pM2G57J6ZuRhD1ToHZvjV/dS8jM1HrUF3Y46KWwQ8fKVkAPmA/7X8zlaouamZBaNDob5UVzmTVlMb7+fRUwr9eHDHPIjpnPSZx/e+a6Bfzkzag8dZdkCIeR2LtwPpzWgj1vU1+ClR14KFBKFH+XiiSKw8/atDwjgR1kow9F23vuWdvFO24K60QcGg86ksgbwmUbUpBatHwRoIqB0mOz9MujRqBKa8O83g6p+NQZtz47VrgbYRwX9FkMiwRRmlJXlk8UStWVLW50KZr4Mw7aFMvz84BSl1uGV39xWIdkYOKOOamA3rQz1ZBL+nON0Ls9neGVPdMehI46G7Ec1EaY0+ttvQOrj+XIrMemIMoSqSO5frncgxVbr6hEiAoHezoduPccEdE/PefikoMLKRocpU3+ppiaff6ICMLc9y4epEsAWCcX7Z8c8d9wCrqkp7gCHVCuNqwxzzmsLM9jG5Gt2Cex0+mffHJoaoPSJLfjyhaQV+1pBYrskBTM+n5EVZQbUOPz3YiXj+aIefT3MEedJxxWDGPV3RYz8Z4UxHWMdy3h3fOWwGq1IAqiQkxV238mSEse+dwLbu8+9/X20B0P+FnmJ989bF2GUEKkcnBjwPlwH8tiXl8ArdCvyGkykf34hqUz/n7QyBj1hH0I6EsLpa/Rp1M/BPsEQD+fTyvLjdLRBAtY5CaMuRU3mwiPM0TofPgnV7GHYMa9A5xJHrs6dR1s5yV7M53jJD4=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-cloud-credentials
      namespace: monitoring
