---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-cloud-credentials
  namespace: monitoring
spec:
  encryptedData:
    access-policy-token: AgCDFOVHLZscBKcwGlX0YeS/8rpAc/+9bh4wibUGfT9oYxL0VAwLyqFLzGwdhTVI0zD4HkxvmsBjd7D7cE1vOiztldYjHWadspBTZ6ZiF8iiGcT1Z6MM8MRnnu+ZKwijTIrdlN7ACymVdPsUp+/K5gd0OoYMs5AKhMqesoQWxrd5b8sDTWkaIuzX+YUIdXiX+BG1IO+iQClwHTsQpb0BPhV//0ehNBRoCVkDEEGA8GzcRsL21J3POLkulyzYDDaKeLuRxD7svmi0BpDfE8BfRFPtgveXoNCBWNURSs5jsm6qcb+jL3RZ5U4OY5c03ECrb35vJ49AV6CjkD12bwWOZwxxAYIizMfYzfxorvkNE+TnGQlujgqtT4pBOWxos31ewbnz5qoQoDULqXli4jOuqhEFJMulujJr1bAVzWyYw2LcQqYcGsoA1Wwb8O1NppiM3FDYepHfjCjgDDJG7sOXX3DYJzj4g1azqKwd1IBILwojn4BheLfQUNgwF/nD+TjeiX4YeKqMHuYpTzVHfF5/gXbjTgnfGqrF8RjuwzoGi7cPfWu2qinvoVYi2AjpR0+1IsfPZuAeppdng+SHdEpcbjRMNrd5P8P4WyD1tEwgnp1eUvfBtXFYVDD398RWRXbYzK8+ILQXHLw0cEi9+4w78pB/Eu1JCGFTGdz1sHTJHEblrmfwcFmQS+Trb4oCHpBRhuRKgI8nZaK8XSYiDxVbbJdnBEvAO5DXyTe2JdrIUj1EeRDVLs0S7PUmlwQh00vL4jOW3+BXSuBphANch3iJMa9A/e8HafgPs43D/F5n3ckhNcEKfguwSpYlTK4jmG0yl8AAdUmHlq71RLp6idamP1cVI5u8HpFyD+s7/Chfl484OxS6JC8fTta0TsugBW934s5MoEll
  template:
    metadata:
      creationTimestamp: null
      name: grafana-cloud-credentials
      namespace: monitoring
