---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBbRBltq3LHDlXwFjnEH1YzIru+bYPdxNsUc4HO2qb6ZASYgevUr36lDABHF94kVuGX3LXoCCKP2PEuhVnixazKUPW0+uVTglXELf4qGfR1GG6PtWOUYBXzQLIAR32oBreBLrKMUIK38shjHlPq73WNe49JVrmC3RdO3UXYvsPOiMu4LXx/2wtWl3v1Wd1u5CHyn84GuseAlcbTZHn+Fb8X/rG0FRq3b25hGz6cXHvE50dStOBx3twwSkmd+eUjbZsan1w+UxMJLgOeKXeph/1XO84JT7xznjNstBL1NnjHuVp71M8QEdq72yYZXw83jgH3pnO0lwQ5cUuw83ufONYWyFsYtkIhcxvqE8BGQrw4Bq0UUESFRFSMYx5XD5dcbGByUl0w9i10mkm2micJP0kTbNpFichI3TSEEKMbibzmAHyQ1vKBjdbsAn7+oDT5Lj/C7mBGsUvd0zpDa8wZNoX0fpRftm4R6P1FQ7uPBFwQfJGeO0FILj9UmdNpQ5HnmMkdexCLN6ShMy8SRGJrvV7l/KOIF23IHJQ/OlMdP/gqpNIRg7FehzVCvjSIXASU215/ezPIhSrfBk57/9nHnlGVUNGh3vGOXO1D0yLqhrEzc/xdoT5YTlXcWUV/+85Q1r0xBF7Y6+CyePgfvdImvHUEd0PxLpa63BMs6VY7YOxNQ2iQqrFdroWGMwIovrqAZXIyczVjhjZuRg==
    user: AgBcI0hlEeF72nCdmzWVriH5wiRm0cWlgE5XkEomM9SDZOM6xbi34REVR6H+60z1OI4Z+TGRm3xlD1L2uG8bnnFs7NX6m1b6kZ2pj4snFtqHCCCDCjZlJZzkH4l0bcvVi4Zg5wGTfk46y/3Fi6W5NWMHHQHimHwCP9umxB81mr84Zkcj/a9/pCV+WnkN2jSpmtpxP1CqOV2mAc3oHhge0yTI5WXRfHDFC87bAsWksJFHg7MIyV5YGOEM/ygQ/EchVzMC/NvFJJxmUQZs67gyld0oq2+AHm2V/aZ+T3PBf/uZPMH+QE5jaxIMZFGfVBOTjb1vErk+wiN8iOAMl+Z9XOSX2mU6uv7554dddRQX/fG0nNTfoezhRvNjRoCdgQHoba7natT1nkSvb3s6ySJKAmidQCjFKZqcepP0AmLDZYRMYb+jcGSSjFqDZwePoxIM/uadipi3FC/kW4N6OkN7jNzpVR6jGjZYA9nC9eSOtPhAMIMMvtDSH4FsjDsy7YjPSH2Sj1eARE0nrVz171+7tYI4hNCk3xuZhG8VDqXk4JEd3UrTL8tqkaHNnJIT/O2w8QGXYu/VV+odZ6a+X9p1+i3z7Nlyd77Gefm/lO5HCuUjw/bj+hcVhNccD4QAB8OrvxKkdgoWimpYahJzSxtS5Y3Qfa4x5Y22E7M/Jn8ViDLvd9t+hze/JiXEyM5lYpSZNTW7tmZgNg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
