apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - cluster-secret-store.yaml
  - grafana-cloud-secrets.yaml
  - rbac.yaml
  - vault-config-job.yaml
