apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets-system
  annotations:
    vault.hashicorp.com/role: "external-secrets"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: default
  annotations:
    vault.hashicorp.com/role: "external-secrets"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: monitoring
  annotations:
    vault.hashicorp.com/role: "external-secrets"
