---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgCq7a+22AlEgyoa0lnRXpL0WJNEQAsHpFMvNhPRJJ/tla8JMrKNSjmS91lak3Wr5d040XjkvYGD3ciK3b0OG2kUJuv++CdqGjbh2fir+bXj/u/ytkOZMBZ2wBI5ES3YfdKeX8Kv504kkVQ+bfHdO8aXMBMxCwpERRhv7QqOPxVokTG3niXyeFSTYBCjwy2OW19jeiTlAVrOdLQlvKFPC2WJh7ilCyADg/n+GFU/8yP97Z6eX+KzVjKUnqebf1ZWcLRLZKg+RZoN3/E2OMDyItu2nTDnB9sUcqh5QLnnHY2rgrKiipVKvXpdgqMSdbFHInCqPRogMnSkHh9cPtBmM/c8sNams+8KwR15n4XJkZ92vzE4ZalWOQAzLqE1pXvJj1LEcE10G95LbPEJTVVMvn4qZwllpvNLZGGcSQ99VkuwHcDuI9FziY/gWBTmd/0M8JQEOq3ReIbyKoFoHSUp3Va2BthV1qyIy2kJg3HqB2Sft3VdG5XMFjIstofPU8ajb11i/sA+Bz49hjUgAmyU7uPrXAVul08OL/3Vh02ZIhmx2fFcYU3wwiZj+KP9G4B122U3V8VeY5P3oa+PDiDaa4ASoJzuTWzy9pYcHR4xWp8bEoUamal2FjUNV2tY0F7PuLbqQ1jdkTmF1mDr9S06NGSZ0gGJJULT8TxPqu1cRsgcMZw3raVPH5YFFxUcIih/dHTWz57Y6+Nw+Q==
    user: AgCQGU/p0TQ0yA9pYtnBPjDeRu5CXhRGeb/UFkLkMB4D1BWvsJPeUSQYtVuL1NLg4ZJ1WimbSCUM6tdBEGxVXBLDXesx1QlYXJJQDX6ll4/6JZGmVdqBo37OqvSkMonHgE4ux+KMr7dQkJF2VM8DG1mfF/b1LIsg/FbTAhsODwZ8UXGK3ei01vdOgG4t/rL7R1JydK1UXiCcV2bIu5Ws0b2jJA4Hd62yyIw2I6cc0x1QrL83+7tlkBmhAuFdyj+8CdNGPUhF9hMM1DITjMDkxf0VNi6GuzLlm3SsctllgH/27kh0KJlSrrdT6V6CNkZlz212K7uZs36kx7VhdE4TP8N8hj8DKWkdciRQ8lY17reZf9FFJxEAFXipwJsaglvYewXiJHCBssOWTYmKuxYXkS2r/KH2PPZ634FSnSl6jm5qHxCEnzNNi8ZtrKZuacw//WKIlhrbuS8sgK+bcHrLWSJsstmzpToP1TIctweAmcXBTMIeKS+ufri4jvmGVyknUsEV3ZrHt2i+ZEXccy8u/K6Ag1EXcS+YNCvH4mQqWlacaIiKRZwPaGPVS6g+BSKId5vAzrv688YhxWhvjQnjW+lsDBPzxTMyGddECeGpfXlwOhuEPREsuTDwhpX9DeumGsmDscxzXNYFsobUncS32ddk1ZTeJQ5lUVBiqpPquu7TJif22drSwUjw3J8TuZsEvBtLK68Tzg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
