---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgCqPWtgYc8VxIP6/3s2/5/Cu20YUepjcuRRBb+jPiRjBrMAyW6YJMrxyFDrUJ4iFdJ7pRVa4LCZD2ic0DP+osFkt0udMbG6mxDys6CLlQGsSQQ3gYv2wNpu5t3M+w8D5zcfeEpIniV7K6ypyLjKerM99rjDktl/jsfUQSzlyMKvWrQoTUwV7JO6exjCoCoO9Iptbxc1AoG5yMw8omTQYiCsxNo4oSyjKD+h1STusGJjTmlobwYCHlWay8n8gZevSzYfb9a6lPhKfNQDBKqX91TtVL1+XbXf4trGXoI/lEyVydfDWpGJWfkEiLYLhDGClHbFvWLlAUdemvAf4OsKwbxO49dSZP2C3ZeiwmL+u6oleQ6N5Igvzvrpy0SJhQm7I08k9PRFifG3HGJAmp5Xl8OBiDoWOj+SgNhicae1qDihPFpGeRmCbsuI5NzvDW6co/mkgGVbxhLYj52AWME3jGsVgmoPgSo6M54sOmv92d+aqgZ/IU6wVVxc+bTixZ3lPrImqGklKaBzAW3auUPdl7D85TcPaWUVlGBIg4g/0dMppa+ZlG/I800bFjXOm1FC68b6wkk2AJ3iiITglIjdvPYO05G4umXceQVfmYpSDqCVP5dJ6xPrNpEOUYMkD7yOu+RhITm5pachc1wZZuZJEsQiG8/S01/mU49ZjD2O0gjG/VATQ4PSQq/3bZz1wMP3NFgiZbJZWUkfAQ==
    user: AgBIIv4546ECiEHSaSZ0KQR3IO8agtmr8bvStUuhpNpzLBi4R856mTia4OicYeDBqvvJE8r2YiAKZbOiGtrHuH2JbGeQTbWBOqEwcbYaaPivyTLSDyOnBccdvWttSqyn2OAPy1mz6kLiedwXAHsschugMChJKKszZfa8u0Pzj70i52/SLvgRMp2MO+Xszx8vaUpnOrCVks2RuHD7aWvLYPISvDuA4qIAnpX5H5ga25bpaUGH501eIykwREPjC1Qtel6LgRlwXiHgpB0RQCzAfJKCT5gITII2Bpa4A051KCTyzkO/wSxAzZyYh0P+B6BBa4VpHvkypnmrRgBxTtkcUUCDghl3LODoTa7IqwKAPWmyFAV+zoEvOD6wXxvEEpWWpLrHcSDdFm0nCE29xCZnDOUM+Hhx/co+S0qL3PfSCVt70m9WmxdCetEAr4Y7351pgYXXIrrLj4L5dsvdqGua4+byv2i+urBjuD7A61fTWss+gbsDdyKGk8enVO/Et6DvpHmxLRD6exrYMY/bEqQwMtiqzkIlKs62opgX3Ql2WJOaJivf/SjS2yOaaLOvwHTP5xrvm8mh+dRlV9mEjfv5sXq7dsDvwW7dvLlVJCBa4ihase2E9mIMFa0sZURO85hA3W5e7LT3X9kHoaoXz7kIiAVy7ic/KFaHcyKRSepjyHcA6Cb4ueTkisP90uIimZi/5rZ0bsQYDg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
