apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  type: helm
  name: grafana
  url: https://grafana.github.io/helm-charts
