apiVersion: v1
kind: ConfigMap
metadata:
  name: sealed-secrets-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  type: helm
  name: sealed-secrets
  url: https://bitnami-labs.github.io/sealed-secrets
