apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vault-init-job.yaml

helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.27.0
  releaseName: vault
  namespace: vault
  valuesInline:
    server:
      enabled: true
      
      # Auto-unseal configuration using Kubernetes secret
      extraEnvironmentVars:
        VAULT_SKIP_VERIFY: "true"
      
      # Configure auto-unseal using Kubernetes secret
      unsealConfig:
        secretName: vault-unseal-keys
        secretKey: unseal-keys
      
      # Storage configuration
      storage:
        file:
          path: /vault/data
      
      # Service account with Vault role annotation
      serviceAccount:
        create: true
        name: vault
        annotations:
          vault.hashicorp.com/role: "vault"
      
      # Enable built-in Kubernetes auth configuration
      authDelegator:
        enabled: true
      
      # UI configuration
      ui:
        enabled: true
      
      # Ingress configuration
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: vault.local
    
    # Disable injector since we're using External Secrets
    injector:
      enabled: false
