---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgAAJmuM9IJJCSHnLRq6m+i/3PnW1taOOs5pMw0E17UFUgBSDqnAB/reOTEa4ddQcXKsd9eRQm530AUw0fLMZwJvq9gfSMZKEG8oFe9SYFsguS3Uyuj0P7AKXhOc/PGfWjpypz72D9H4hXN1o8/+q9W1D0jCFqxHBJW3lx5iSu60aPCGzG2SdBh3AXDEa/S6eik2BC+pifG1QHvCaaDbfgl1CXV4JtcSAbKnYPfk+v9JcCBf5thUxm4TrL/31opewa+L7Yg51Fqkn7qxm/LI1H+wgeH/PqTAimlTPK6zWVYDHPqQqWEzD8pqFbNbJiTFxckqWeABrbozQ0WKnZoibd3ysxaV9vJqYryjGKfVvl9gBZik/+tSkGFhAOvYP2Vz3ILT4ysPr+QDaqXGgtoLcZlXCDM99SYXI9aT0nGKR9XewGXTDRvIhPvyseDnH6TdZSIzA03UD+6z0P1HTsZzo9nyqWV3GAwEsQFmxMs6fK5aWXaw8oZS0pRo0drBHhpWANRvVodjrVZOIrZAsinJJnZVaQmKZN8aRX5xWtASdOtgjv9BnjdW5sb0r2oTdkAD7cE6+pfAHywhjKsCDCNexBmVwVNcyEU0OX/RsF0nuNMGHLv05iJjwvM+OHQVgeyfOPgzOi+6Vebh3WRjVakN/0dMPn0Mf8vR7UrGaxbm5TzkrvJnGD65eGcmZFVX9gV44W39fN0AOEl30yudmD0vvu+e1fMyANQJ/WrxvyHORIEPd135J+UrAY8HpI+tYOxYI6/dE7xRkfERTCmxoiYL
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
