---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAv2051pPv2q897TF5t84t9nYhF/JzBc/7OBH+3N8NpfLAJ96z/OlyR1NbOro3Nqw+00gFE7KtUVjrZ3mjG/oj/FCt9HUtTL5EygLRgjITY9f3Bg25mS1JxkGuGVogCuaecbmAAeWnSMO4Ni4OPryJNADEtzJ58hPazMDfeyRPOz0mD0tzF+1U5K4wLLSX/XrlH6sviaYEGh0yAaX1kTU4Gzv0lU8b/7v9iUUvH5GDgBQ1nruzxbYkRYy0c7v2mWjKlWoiaz1o1r+Doq9xa4jMoAQ8hFRTBa5LtkC/KcJ+Xzz/t5tKKEd6d0jlppNesHT/NAwjQmDI5/K0wu8BtwW2FI/TllEPGvciOa/d0UORoR6SNoH2vm8QG3uXNXENl6e8iuS3TzWgsUczwhuez+9H9iX4lXnZ54bS/Xt/LaXMVzJRs714QLNx/3M7SG6dqSUo2PJXgq1+OXoGidIA7E7F37eV6vV4GSRNDr3HBJ1t0Oww1yumUFXLyejcqdEnnBbt9wYZzd0Nr2gch7F6dHFFE1K5f9zFkg9SXKGdA0YY7Yz40MumUHKL3YxSug9b1T3qZGnbYSHikidVfOi4w102HMCvTCWwy4N8oe/1+CWNpCY9y8OVmcPfj7nzHrTFClIfxP8vylDwZuCrbiIoQm1mY5Bn6vMXHGCFF7s/bHa38iPDcpVoA4RjSBgNdzwdzg8sJUJTgfN4BGyy1PNcXfMo5yg==
    client_secret: AgAvaOQIW/Ji42WsqsWF9ogwYKHqe1RZRaYkkMqWYXMc/n5kbel/Tspge2aZ9AhIghdM0aZ0rxwV+OaAlPytcZf3AaqAkUYcy73q/JLArKCKwEwPELAJTQEA3FUZFlascrfvyhnpmt0VMK1xVak2mppEctZavOJyEPtDY1oi8bShJIlnHyDnR501nshkmlmZJuAUpF6zvf/Yd5t5KyPSTrzJ4u1yltXfg0QiYVLJsYrhz2khPX+s57aGM9Dv0cPdgBTujs4P1CzEt5OJwWR9uISudow5vOhi/BnQRynj3zaJvQrUceb/HZ6T5r8N7s75ObSxlVExcsAGSZiYRh3yIbil0hYUAOtEoU6+EU6VRdXK+Y6UevxlcWpqt4Jzba2K2TDcSSVim99y44OwUjxrkiSgNsZyHCJan8rHl9ooyE5Rel2+z2Ty/0XUZyxUYNEwxwAaraHgrf20DxltJ4768+42wLkQwjilY/84jWprvG73RZ/kXC9l72qQ7fCe5CDYwJ0Gay6J0Povnp3OwWN6iszYM5CfuToXUu/8FDluSw10mPttw+Y29Y/WPa9DOIGpN27yaQutnavk3mGwUyGxWlgFCyaN0QlX3RilSzUJAk9MURNrAC6TH0k8fMlp0wl5zk0zJKWu9FsjelhycdFNPY/NgKL/ch0TYceITLp3ymr53HRs3IK+Tm2VL+coIeHYpco+vMI6g3JTRMdTbcWH2TS2rmlMeB+b6b6svcMw5MlTMP7RtwdvjkN2hTW3OsikX24GtkU0FWsEDhdn0tuMeg5b
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
