---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCxFYkhngCgjoEWx7he6bPcUiUKBWs7MzQ+BjhuLaMkQq86Vm0d/mjZ7k8OlT7vJ3DCDaoPizD6OWLVHhlmHpo5WXLfG1dB9pHntT8DlOIG22S/ig8t2cQNszt8Ed2rIcHSYUBfOwJIh7wm8l93BcmHncBronbvjuHFvmT8xWIVfE+jtFS9iZcqX52rW61j6mIOn3Q5W8QwrY9SEHEXa3Tjhwam08NgxRdmwkawFfqT7Xi3xlxno/9PqsOuUrklKrQwF1uCNcsuKGdcEGPuS/nJHqZZIYavA3lXIyZsNb5KBPLsEj719eNJuUG7RuvCAk8UdE8kXxVb2HHDdW0U6/4+LBUfe0BYh4l8GeQpAKJmMKBz8wEgovjE+5QXCindS/zkSxJ5e8r62Mu0aFH3qxGsuCdZ0IOC5nBz58K4+ypyxXzqGLewPw4MZY/yG1dyC7jw6xQbeJuW8o7iONzC9GPh3Czs/1JzK8RnIUjY6JcrqZnRWi8itPreNYhkGdEa+qEMlOQziJKpWTKCpo9sIcECYdxMV/vTuXI5vKjaj4olzYSa7b+qKn6XBfKvjuLuFpq8ujrJ4UOEBjcIc72tO8BOZHKJ/EBH+05/L6rs0Y97QU/vQWTytbvS/8V6K51TBbgOUJt5TBV/M/6nImBBoz3lv2ILWtt04c5nDjoAnN6oSM4NO/tldyjGeRKvft0z6mugN/Yx4rWTNZdITs08AlP1gg==
    client_secret: AgA8RjfYtT4cuPqDQEoWCvFzvLGwI4fgW3WtiotSfpAlAa5oN2gn0OhXeQzSalA1fFZaSNzVhAdqxP8hd/EmzEFTPeEbDSTmbyxSXBVuhdAzQEp2YK+Yw/2DlczA4zNV1dxo5kZ00/PNglol1KIeGoMi0mRmInPKnkwqqbTVm5uqM2D96kTOO23eWQKz/pdJZUIIZpv+sWL8Ju+RmQFVA3gEJPFxDnYFDFMmZyoUvwpvNSYqrtEBdlCkJQOxbTYfk3m1K/B1CHs9jvLHkq3vTbpbKjR4SWWkQZmZTpUUtLNCsa9xGTMTlEfIT/cMM+brsPCLNmP4hwVmzqsGjkFaUKBtfL6P7wQSe1i6aMEl76HXc+brWu6nvFnM06cezcg2OKdNB0hemNaE516xvy4iDmrA/sjnmoTwGmNfe2RunnYJWPTX9/9LPnC+g93So821xGEhQqapQWZeBtQytfGWb2Ni7BccXLNXcosB3oxESAV1/o9XIOqd8JMS3UMeM3BlCwp+aCuoNEEo/vq10HKUfQ1ZHLx7tp6YNHZGvOAZVnDKnkvRg1euwKVWvd8bqc3dr0S2QvkvEojnJyHdUSicLK4QVoNtGJjRFlGaoP3AP/YBxRlXOQdBkGifOQJANhI1NygzfDmv5KuvGnXaTL0eEWUjy+EPhY0eutrnjZeLq03X1LyzdupS413Wy3m7siwKMxpQjF+JxlHjflpxUGoVPGQgFXbzflB3zZSizV93o4uHylt7QkqA14igEVD3M+NFn2XVT6IlvSiiX9kuDm3bS9Qf
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
