apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: ssh://git@github.com/nullcap/infra-k3s.git
      revision: main
      directories:
      - path: argocd/manifests/archivetw
      - path: argocd/manifests/traefik-config
      - path: argocd/manifests/sealed-secrets
      - path: argocd/manifests/grafana-monitoring
      - path: argocd/manifests/argocd-config
      - path: argocd/manifests/uptime-kuma
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: ssh://git@github.com/nullcap/infra-k3s.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true