apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-app
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/nullcap/infra-k3s.git
    path: argocd/applications
    targetRevision: main
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
