---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgCiGt3cPCHuOlHdpwOT7b+INfYt0iLes5J96XhdR/YOkEd9OhzJYzDxI54a68mKOusz2pT0leSyoiGjnZpDDfQqHc3q1/wA3E/Bn4bBoNf/zfaYbQ1ARjgJaYaB9h1K+EXKLCWHhtuRBXf6lPgBvyBN0ucarlHKsXctPQCMmdMttnPFvI6EWjFrc/2VVJLziVgipDJcSPxib3ltD8CT/y1jpVVksHvLneE3aW7ygfMTbUUmCutvtZ+sAvYeTjuCDnIhvLFhabOikZzikKIhiaI/CtfPv222CBI9Ejq9Pe5NfT/OWlspcfAaPHiC9vjQhFfQ29NJUbrmYhF8YgNZkvJGSEuzSe8xdTUisojgzMncxnlvKXVOQ6fr1oUUnwwSNqvGD9FJh9rAb9DXG9d8ohGkmziYOgaaKUBHr62WI9c6jb2ZcoF6OwZXZ9hHfdNFhXA33f4QUFAoY3Vy8XQqsJQijQAAw1CyMQ1YvHz3qqG563gX0XXGLk5pPt+owDZ23m8lzDMRT10beCCSpnid8klahvfX7acP/18C5wJBr5X9CpmpQjs4SsPnPKCay2XvWf9A5jpPfEHiKiljc4hAfb9tHONgBTC/PsmUtSmMeiwqH0qkCpkbAU0gC1GmjAtSF5Ls56Vya/1g8NIXZ8JgFLDEQgb22u6BUBN981Zo4jHBwXtt9WE8kjlGu9sus05jRYXrIZlmyp/Ugw==
    user: AgA7rCpu7LixNBL+qDGkvqA0uc+OFFhz4lg5Tt0E/FwwZdnI83Bq4kOfGk42xWgfBwI7oeDFrY49Jqj6+Y8N3cPGxfJFdQcrX7LweJuHy6wa2/iCO5dyPwB5aUk0URGHoljWfEdfalaoRUnYRyMalhOG60QsONZixM1WyTH5FmssyQBmE3u6/Yjkfy7MKwjph/sCX2rCx1Qd1mTx0BJhBJdqRVYBk+qawYJRdNKJMFse8C3ukbXv3x1SdsdE1w5fnscrwW81pbysosI+xZnXYvysx5QNMNkSj3g5q8TYawO0C7B1IQ2a/K3OVh5qhJ5YRKPTn8yqerF+ZS2hE5jZFr/CIDND15OKWV2cDnBKuxrtVm6xvYUN8v+t8eZI38PMMH5x9wxHUIyedlvElnpLvYriaQqq7gVsD79I4WTjG30VbphtLg010ekMlLtoxROrn9Q9RrywqU81i0rKlYgbUVqi9JGh75RKE9241PwSOt2OBw/amluEncNZ6z6+BjFDx9QiPWzKKi9v/y9PcpRJTfXjLFgcLq8U1qD2oJpt1mT8EPXJ/LtaMtvP80E/XlJODDvA6KWA6VgJtUAR42ypNfDwuoF6KEHZBae+8mUg5IuRHAmIfdkujakDtC12bwlkgmyfYQTQKzzccHQIMgbmsvUFO1BNQ678TDqZ+eLdeqBWQoK7j1sdErE/n6KgTviP4CJ7q2/bEQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
