apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.8
    helm:
      values: |
        global:
          domain: argocd.nullcap.net
        
        configs:
          cm:
            # Enable server-side diff by default
            application.instanceLabelKey: argocd.argoproj.io/instance
            # Enable experimental Kustomize Helm support
            kustomize.buildOptions: --enable-helm
            # Allow applications to be deployed in any namespace
            application.namespaces: "*"
          params:
            # Configure external URL to prevent redirect loops
            server.url: https://argocd.nullcap.net:30443
            # Disable TLS since we're using ingress
            server.insecure: true
            # Enable server-side diff
            server.enable.proxy.extension: true
        
        server:
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - argocd.nullcap.net
            ingressClassName: traefik
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.nullcap.net
        
        # Enable the app-of-apps pattern
        applicationSet:
          enabled: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
