---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-cloud-credentials
  namespace: default
spec:
  encryptedData:
    access-policy-token: AgBIuvSqDVa2RwoszUdBTH/iiIKBihM+4CduUPjEDx/CeVYeP05t/jW219WdRcmW5/b1lKVEhvB8dHVyC1DV8uwLWBLAEGnkKAFydDg6KrgTmUA7+sVYRPPYoVDeAVtmnBP3+PzzzR/cz2wMBUk5WZXAzrOA3wq/sD4RkhO0hu2Q5/6t+9RBMcEiacutWQihb428g7GrA7NmzbyoWokGt+71OFGe4a3AcpA4d8apXHLv8g1fZjkN9C4umnhIfbMffd8gL/kAhlTyxr1ATa9Gl5s7DV04eddO6MgiC83v0OKtrm548aBQrH5qxgi3ObZhKQBBZKRXdrcUklHn1mzXmePxNav7vz3Lha7mWMmhnO002T3TFxc7t+ev+vVYqyIO4konz4pZHCP6a1iXWb7L9Z/C4AYWm9Hj673esn8hyco39CtyDdfjUHTCRy53IA7tATeC4Jgis194/tecRwKmTjqeilKehzTbtatvcBIDpqbq60558Bi8O6N21E0K+rUpJmEAgVvIyarqN4RcPNIzhTvKk+NzAfeA4xeheP+/4r2+OgXwklzc5uTfg6o7Hcvre6RtsK7epsSnB9LlCiHtqmWmu8GrDMVewMX6+2emV3ZoUpyfJv0wZ+PRXimYDvX+9W4AQM6nU/vyv1dwpyoDShdj8kqYGmsuEJx3hFohA0l4XyBNFS+YG9z34ap7enRlG6eNFMvLr00MdrxYyo+/RW1Fy/6+PsG6soba88aulu4exVGzO84y2eRsTHO54//nG3Fr9qEeSdRzkGQCPC7Tj9PxW1o/WYULqoxJatg+w2iGDryvQE4mN5Jsqh9nzCoZjUCQ2O2jjPf5FjneioAOaFsBlCgshy9yk8DOXcxnJs16kOEJfxXW+CKzM/OOMAZFN3pbDP+l1linn8BHeEx0bFDCnz0YdPhRGRg=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-cloud-credentials
      namespace: default
