apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivetw
  namespace: archivetw
  labels:
    app: archivetw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archivetw
  template:
    metadata:
      labels:
        app: archivetw
    spec:
      containers:
        - name: archivetw
          image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest
          ports:
            - containerPort: 8001
          env:
            - name: DOWNLOADER
              value: "nullchive"
            - name: SELECTED_PROJECT
              value: "auto"
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: archivetw-service
  namespace: archivetw
  labels:
    app: archivetw
spec:
  selector:
    app: archivetw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archivetw-ingress
  namespace: archivetw
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: archivetw.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: archivetw-service
                port:
                  number: 80
