apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager-config
spec:
  project: default
  source:
    repoURL: https://github.com/nullcap/infra-k3s.git
    targetRevision: main
    path: argocd/manifests/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
