apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets-operator
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.9.5"
    helm:
      values: |
        installCRDs: true
        
        # Configure the operator
        serviceAccount:
          create: false
          name: external-secrets
          annotations:
            vault.hashicorp.com/role: "external-secrets"
        
        # Webhook configuration
        webhook:
          create: true
          port: 9443
        
        # Cert controller configuration
        certController:
          create: true
          serviceAccount:
            create: false
            name: external-secrets
        
        # Leader election
        leaderElection:
          enabled: true
        
        # Metrics
        metrics:
          enabled: true
          service:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8080"
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        
        # Resources
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    namespace: external-secrets-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
