apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: grafana-k8s-monitoring
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: "*"
    helm:
      values: |
        cluster:
          name: my-cluster

        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
            auth:
              type: basic
              username: "2600859"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: metrics_api

          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-036.grafana.net/loki/api/v1/push
            auth:
              type: basic
              username: "1296106"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: logs_api

          - name: grafana-cloud-otlp-endpoint
            type: otlp
            url: https://otlp-gateway-prod-us-east-2.grafana.net/otlp
            protocol: http
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: otlp_api
            metrics:
              enabled: true
            logs:
              enabled: true
            traces:
              enabled: true

          - name: grafana-cloud-profiles
            type: pyroscope
            url: https://profiles-prod-001.grafana.net:443
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: profiles_api

        clusterMetrics:
          enabled: true
          opencost:
            enabled: true
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: my-cluster
              prometheus:
                existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                external:
                  url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom
          kepler:
            enabled: true

        annotationAutodiscovery:
          enabled: true

        prometheusOperatorObjects:
          enabled: true

        clusterEvents:
          enabled: true

        nodeLogs:
          enabled: true

        podLogs:
          enabled: true

        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
          connectors:
            grafanaCloudMetrics:
              enabled: true

        autoInstrumentation:
          enabled: true

        profiling:
          enabled: true

        # Alloy configurations with proper secret references
        alloy-metrics:
          enabled: true
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-008.grafana.net
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: fm_api

        alloy-singleton:
          enabled: true
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-008.grafana.net
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: fm_api

        alloy-logs:
          enabled: true
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-008.grafana.net
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: fm_api

        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-008.grafana.net
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: fm_api

        alloy-profiles:
          enabled: true
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-008.grafana.net
            auth:
              type: basic
              username: "1338312"
              passwordFrom:
                secretKeyRef:
                  name: grafana-k8s-monitoring-secrets
                  key: fm_api
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
