apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-grafanacloud
  namespace: argocd
  labels:
    app.kubernetes.io/name: loki-grafanacloud
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: "*"
    helm:
      values: |
        test_pod:
          enabled: true
          image: bats/bats:1.8.2
          pullPolicy: IfNotPresent

        # Loki is disabled – sending logs externally only
        loki:
          enabled: false
          ingress:
            enabled: false
          persistence:
            enabled: false
          isDefault: false

        promtail:
          enabled: true
          config:
            logLevel: info
            serverPort: 3101
            clients:
              - url: https://logs-prod3.grafana.net/loki/api/v1/push
                basic_auth:
                  username: "your-grafana-loki-username"
                  password: "your-grafana-loki-api-key"
          service:
            enabled: true
            type: ClusterIP
            # Port is optional when pushing externally

        fluent-bit:
          enabled: false

        filebeat:
          enabled: false
          filebeatConfig:
            filebeat.yml: |
              filebeat.inputs:
              - type: container
                paths:
                  - /var/log/containers/*.log
                processors:
                - add_kubernetes_metadata:
                    host: "{{ .Values.nodeName }}"
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers/"
              output.logstash:
                hosts: ["logstash-loki:5044"]

        logstash:
          enabled: false
          image: grafana/logstash-output-loki
          imageTag: 1.0.1
          filters:
            main: |-
              filter {
                if [kubernetes] {
                  mutate {
                    add_field => {
                      "container_name" => "%{[kubernetes][container][name]}"
                      "namespace" => "%{[kubernetes][namespace]}"
                      "pod" => "%{[kubernetes][pod][name]}"
                    }
                    replace => { "host" => "%{[kubernetes][node][name]}"}
                  }
                }
                mutate {
                  remove_field => ["tags"]
                }
              }
          outputs:
            main: |-
              output {
                loki {
                  url => "http://loki:3100/loki/api/v1/push"
                }
              }

        proxy:
          http_proxy: ""
          https_proxy: ""
          no_proxy: ""
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
