apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.27.0"
    helm:
      values: |
        server:
          enabled: true
          
          # Auto-unseal configuration using Kubernetes secret
          extraEnvironmentVars:
            VAULT_SKIP_VERIFY: "true"
          

          
          # Storage configuration
          storage:
            file:
              path: /vault/data
          
          # Service account with Vault role annotation
          serviceAccount:
            create: true
            name: vault
            annotations:
              vault.hashicorp.com/role: "vault"
          
          # Enable built-in Kubernetes auth configuration
          authDelegator:
            enabled: true
          
          # Use default readiness probe configuration
          
          # Let vault-init job handle initialization instead of postStart hook
          
          # UI configuration
          ui:
            enabled: true
          
          # Ingress configuration
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - host: vault.local
        
        # Disable injector since we're using External Secrets
        injector:
          enabled: false
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
