apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.27.0"
    helm:
      values: |
        server:
          enabled: true
          
          # Environment variables
          extraEnvironmentVars:
            VAULT_SKIP_VERIFY: "true"
          
                    # Service account
          serviceAccount:
            create: true
            name: vault
          
          # Post-start script for auto-unsealing
          postStart:
            - /bin/sh
            - -c
            - |
              # Wait for Vault to be ready
              until vault status 2>/dev/null; do
                echo "Waiting for Vault..."
                sleep 5
              done
              
              # Check if already unsealed
              if vault status | grep "Sealed.*false"; then
                echo "Vault already unsealed"
                exit 0
              fi
              
              # Try to unseal with key from environment
              if [ -n "$VAULT_UNSEAL_KEY" ]; then
                echo "Unsealing Vault with environment key..."
                vault operator unseal "$VAULT_UNSEAL_KEY"
                echo "Vault unsealed successfully"
              else
                echo "No unseal key found in environment"
              fi
          
          # Environment variable for unseal key (will be set from secret)
          extraSecretEnvironmentVars:
            - envName: VAULT_UNSEAL_KEY
              secretName: vault-unseal-keys
              secretKey: unseal_key
          
          # Enable built-in Kubernetes auth configuration
          authDelegator:
            enabled: true
          
          # UI configuration
          ui:
            enabled: true
          
          # Ingress configuration
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - host: vault.local
          
          # Vault configuration
          standalone:
            config: |
              ui = true
              
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              
              storage "file" {
                path = "/vault/data"
              }
          

        
        # Disable injector since we're using External Secrets
        injector:
          enabled: false
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
