apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-unseal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: vault
    targetRevision: 1.9.0
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true
        
        server:
          enabled: true
          
          serviceAccount:
            create: true
            name: vault-unseal
          
          # Use custom configuration
          extraArgs: |
            -config=/vault/userconfig/vault-unseal.hcl
          
          extraVolumes:
            - type: configMap
              name: vault-unseal-config
              path: /vault/userconfig
          
          # Disable readiness probe during initialization
          readinessProbe:
            enabled: false
          
          # Use filesystem storage for simplicity
          dataStorage:
            enabled: true
            size: 5Gi
            storageClass: ""
          
          # Disable HA for single-node setup
          ha:
            enabled: false
          
          # Disable UI for security
          ui:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-unseal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-unseal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unseal
  namespace: vault-unseal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unseal
  namespace: vault-unseal
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unseal
  namespace: vault-unseal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unseal
subjects:
  - kind: ServiceAccount
    name: vault-unseal
    namespace: vault-unseal
