apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.27.0"
    helm:
      values: |
        server:
          enabled: true
          
          # Auto-unseal configuration using Kubernetes secret
          extraEnvironmentVars:
            VAULT_SKIP_VERIFY: "true"
          
          # Inject unseal key from secret
          extraSecretEnvironmentVars:
            - envName: VAULT_UNSEAL_KEY
              secretName: vault-init-secret
              secretKey: unseal-key
          
          # Unseal configuration
          unsealConfig:
            secretName: vault-init-secret
            secretKey: unseal-key
          
          # Storage configuration
          storage:
            file:
              path: /vault/data
          
          # Persistence configuration
          persistence:
            enabled: true
            existingClaim: vault-pvc
          
          # Service account with Vault role annotation
          serviceAccount:
            create: true
            name: vault
            annotations:
              vault.hashicorp.com/role: "vault"
          
          # Enable built-in Kubernetes auth configuration
          authDelegator:
            enabled: true
          
          # Auto-unseal and enable KV secrets engine
          postStart:
            - /bin/sh
            - -c
            - |
              # Wait for Vault to be ready
              until vault status; do
                echo "Waiting for Vault to be ready..."
                sleep 5
              done
              
              # Check if Vault is already unsealed
              if vault status | grep -q "Sealed.*false"; then
                echo "Vault is already unsealed"
              else
                echo "Auto-unsealing Vault..."
                # Get unseal key from environment variable
                vault operator unseal "$VAULT_UNSEAL_KEY"
              fi
              
              # Enable KV secrets engine
              vault secrets enable -path=secret kv-v2 || true
          
          # UI configuration
          ui:
            enabled: true
          
          # Ingress configuration
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - host: vault.local
                paths:
                  - path: /
                    pathType: ImplementationSpecific
        
        # Disable injector since we're using External Secrets
        injector:
          enabled: false
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
