---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBORbd/DtEzO//UhUUTigFEee0ajUyU+DEKP2yxxTfIAPuZGR0rS8S67pD0FNxHgRngXgnflq1O34scyLCJp+MM0GkD584cpJy/9oytPr9nKLFSbXUFQfAEkwEBa8moa5ZyQnLk3P0oKmFvY1ljgxCDd2gGVLMXSDgKTVOpBJC8+cQelWP0HjlbI7ROtr8FpMqotuTXcw7rpas06OvO8GyzT4j9lPcfpBU1GqDNrRgEjsPayNxcpmbWXiLt0GpFNuRL+QjGMC9/BLjmje7g/v2BL7sZjI88ThQ1Ry/Rj0hoRrxeIjSImY0nfJYXvEDku14MMrokCI5uGGNBRuUpWQW67ZmDxczXrTmyK6t7WpZ1oUm1pMmwQKDBAk/pTeLaoB/rKXhbjk/brhwxqPJO1uqLhMrtbJrHlHFb5w76fhFZJ6Q85IGmj0ugx5dNVosrkG4TElSxRCB/RAhO8zqTbBDmN/PY23OW1RfZy8Y5rk/ObjSFVCaGf1TR+345A150Yk3fRq0My4SyMyW+sPabLLj8lfrRC+KxdjqARhdBjVEU4nlmhO5/tpvuz4HgGnNqM+PjkH4r1zStJfKSV9FVZ1gCrX3zvtmmUp5KCzyLCIweTjpVaPooQPtRq4KGjAknY9hUQLQkvn47GeKgWWbZwKvGjQjzV65GO4kPfKQHwmB1mxZJgC60OND7PH7U6kh40o9GJrAB9fz53b5UR+0yS+i8aWI96hrp3xNLT44XMUR/OMZ0JgQwP5qm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
