---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCPwZ3yuUI2gSUoOxAqV6zl6aLZB7wu2Q/g7tKMyq300HZJOzhOBqf2Wg5Z5yEAo1TnChv1O2zgJSrY3n2c9c7pECMe9VWTvdecr4XvtxcF7skbWlf1X+/29BMfosKhbKXgEsfMl0GgiTRg5AWlvLgLiGFxM2+pkcGs02KD+vao50GG7sseUDSfKHwfaTw6vzPo4z00JLLFfpOBTAGz8up7pZhdZWwJeO/FFHBQ/zFl316yiokaIg94fDpP3kFfg4YVdlI9HsHOVYy3qZ2CFaC1/WhT+FILjL32c4fP/IkKHUHi3QjuYaByP0bPIeQr5Fj6HBi+EeiCls9aZSan4oXp1fFmvE+YPbeSBBLaXH6FVNWqa3/7OCOnrMr9+KC9yuE1vzifCF3KDxS7AC6oKTspsIo+xR/HvzK/ZV+iY5R/CssnsjMmE1JAWN2C6SYRHYbbHa1e0TDl1hvbRZBenVEqOJgffakJDD7jIH1rUuxMPwSIzWi2abAtbTyF76dqxAcH9Mz1SoTM2zVvnM00THlGMWXo7zn9Czk0/UsW6IDpFCb5vbfkR4VXd3/kC9HBsUk/t9lDR/nLXrdQtjEoaDYfkjdbMQlhHmB4NkmgGAhXm2Azny6Kl3FXTY39S/ykiay34cfLushz0mIV8PUBwjxgxWNHs+G0daUYQC5gdFIWmGCsqxMqcaDI03DnE8pOY67p3H8EpBBekAM5JmisN9VChf1H55RpIjY9CkKDUyiEL2I6/pQiaSYu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
