apiVersion: v1
kind: Secret
metadata:
  name: jetstack-repo
  namespace: cert-manager
type: Opaque
stringData:
  name: jetstack
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1h
  url: https://charts.jetstack.io
