## Configure traefik to use ensure we know which ports are being used externally on the cluster. 
## This file needs to be configured on the host @ /var/lib/rancher/k3s/server/manifests/traefik-extra.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    priorityClassName: "system-cluster-critical"
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ports:
      web:
        port: 80
        nodePort: 30080
      websecure:
        port: 443
        nodePort: 30443
