apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - alertmanagerconfigs.yaml
  - role-prometheus-adapter.yaml
  - traefik-helm-extra.yaml
  - monitoring-pvs.yaml
