# Namespaces are configured in a seperate file so we can configure things before deployments.
---
apiVersion: v1
kind: Namespace
metadata:
    name: usenet
---
apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
    name: pubnet
---
apiVersion: v1
kind: Namespace
metadata:
    name: archivetw
---
apiVersion: v1
kind: Namespace
metadata:
    name: tailscale
---
apiVersion: v1
kind: Namespace
metadata:
    name: vault
