apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace: nebula-sync
  labels:
    app: nebula-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula-sync
  template:
    metadata:
      labels:
        app: nebula-sync
    spec:
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PRIMARY
              valueFrom:
                secretKeyRef:
                  name: nebula-sync-secrets
                  key: primary
            - name: REPLICAS
              valueFrom:
                secretKeyRef:
                  name: nebula-sync-secrets
                  key: replicas
            - name: FULL_SYNC
              value: "true"
            - name: RUN_GRAVITY
              value: "false"
            - name: CRON
              value: "0 * * * *"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
